name: Build and Deploy

on:
  push:
    branches:
      - dynamic

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Install Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7.x

      - name: Ruby Version
        run: |
          ruby -v

      - uses: actions/cache@v2
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Bundle install
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3

      - name: Middleman Build
        run: |
          export TERM=xterm
          bundle exec middleman build -e production --verbose

      - name: Prepare Release Asset
        run: |
          tar -cf h-lame.com.tar public
          bzip2 h-lame.com.tar

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/h-lame/h-lame.com/releases/37054526/assets{?name,label}
          asset_path: ./h-lame.com.tar.bz2
          asset_name: h-lame.com.tar.bz2
          asset_content_type: application/x-tar
